// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package testinsert

import (
	"bugtest/api/testinsert"
)

type ControllerV1 struct{}

func NewV1() testinsert.ITestinsertV1 {
	return &ControllerV1{}
}
