// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"bugtest/internal/dao/internal"
)

// eventlogDao is the data access object for the table eventlog.
// You can define custom methods on it to extend its functionality as needed.
type eventlogDao struct {
	*internal.EventlogDao
}

var (
	// Eventlog is a globally accessible object for table eventlog operations.
	Eventlog = eventlogDao{internal.NewEventlogDao()}
)

// Add your custom methods and functionality below.
